disabled_rules:
    - opening_brace
    - comma
    - colon
    - vertical_whitespace

    - line_length
    - todo
    - force_unwrapping
    - operator_usage_whitespace

opt_in_rules:
    - closure_spacing
    - empty_count
    - explicit_init
    - force_unwrapping
    - missing_docs
    - overridden_super_call
    - private_outlet
    - redundant_nil_coalesing
    # - conditional_returns_on_newline
    # - switch_case_on_newline

    # New Stuff
    - attributes
    - closure_end_indentation
    # - explicit_top_level_acl
    # - explicit_type_interface
    - extension_access_modifier
    # - fatal_error_message
    # - file_header
    - first_where
    - implicit_return
    - implicitly_unwrapped_optional
    - multiline_parameters
    - nimble_operator
    # - no_extension_access_modifier
    # - number_separator
    - object_literal
    - prohibited_super_call
    - redundant_nil_coalescing
    - sorted_imports
    # - vertical_parameter_alignment_on_call

excluded:
