disabled_rules:
    - opening_brace
    - comma
    - colon
    - vertical_whitespace

    - line_length
    - todo
    - force_unwrapping
    - operator_usage_whitespace

opt_in_rules:
    - closure_spacing
    - empty_count
    - explicit_init
    - force_unwrapping
    - missing_docs
    - overridden_super_call
    - private_outlet
    - redundant_nil_coalesing
    - attributes
    - closure_end_indentation
    - extension_access_modifier
    - first_where
    - implicit_return
    - implicitly_unwrapped_optional
    - multiline_parameters
    - nimble_operator
    - object_literal
    - prohibited_super_call
    - redundant_nil_coalescing
    - sorted_imports

    # Disabled on purpose
    # - conditional_returns_on_newline
    # - switch_case_on_newline

    # To reconsider / temporary disabled
    # - explicit_top_level_acl
    # - explicit_type_interface
    # - fatal_error_message
    # - file_header
    # - no_extension_access_modifier
    # - number_separator
    # - vertical_parameter_alignment_on_call
    # - explicit_acl
    # - multiline_arguments
    # - no_grouping_extension


    # New Stuff
    - array_init
    - contains_over_first_not_nil
    - discouraged_object_literal
    - discouraged_optional_boolean
    - explicit_enum_raw_value
    - joined_default_parameter
    - let_var_whitespace
    - literal_expression_end_indentation
    - operator_usage_whitespace
    - override_in_extension
    - pattern_matching_keywords
    - prefixed_toplevel_constant
    - private_action
    - quick_discouraged_call
    - quick_discouraged_focused_test
    - quick_discouraged_pending_test
    - required_enum_case
    - single_test_class
    - sorted_first_last
    - strict_fileprivate
    - trailing_closure
    - unneeded_parentheses_in_closure_argument
    - yoda_condition

excluded:
