version: 2
jobs:
    build:
        macos:
            xcode: "9.1.0"
        steps:
            - checkout
            - run:
                name: 'Install swiftlint'
                command: HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
            - run:
                name: 'Make /Library/Audio/Plug-Ins/HAL writable'
                command: sudo chmod 757 /Library/Audio/Plug-Ins/HAL
            - run:
                name: 'Build & test'
                command: |
                    xcodebuild \
                        clean \
                        test -scheme 'Pancake driver (launchd)' \
                            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
                    | xcpretty \
                        --color \
                        --report junit \
                        --output ./build/reports/junit.xml
            - store_test_results:
                path: ./build/reports/
            - store_artifacts:
                path: ./build/reports/
